src/rfdoc/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.views.static import serve


import rfdoc.settings as settings

from rfdoc.rfdocapp import views

admin.autodiscover()

app_name = "rfdocapp"

urlpatterns = [
    re_path(r'^admin/', admin.site.urls, name='admin'),
    re_path(r'^upload/?$', views.upload, name='upload'),
    re_path(r'^search/?$', views.search, name='search'),
    re_path(r'^lib/([^/]*)$', views.library, name='library'),
    re_path(r'^lib/(.*)/(.*)$', views.library, name='version'),
    re_path(r'^$', views.index, name='root')
]

# Force Django to serve static assets, if this is not the production
if settings.PRODUCTION is False:
    urlpatterns.append(re_path(
        r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT
        })
    )

src/rfdoc/rfdocapp/models.py
# Copyright 2009-2013 Nokia Siemens Networks Oyj
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.db import models


class Library(models.Model):
    name = models.CharField(max_length=80)
    doc = models.TextField(verbose_name='Documentation')
    version = models.CharField(max_length=20, default='<unknown>')

    def __unicode__(self):
        return self.name


class Keyword(models.Model):
    library = models.ForeignKey(Library, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    doc = models.TextField(verbose_name='Documentation')
    args = models.CharField(max_length=200, verbose_name='Arguments',
                            help_text='Use format: <em>arg1, arg2=default</em>')

    def __unicode__(self):
        return self.name


class Init(models.Model):
    library = models.ForeignKey(Library, on_delete=models.CASCADE)
    name = '<init>'
    doc = models.TextField(verbose_name='Documentation')
    args = models.CharField(max_length=200, verbose_name='Arguments',
                            help_text='Use format: <em>arg1, arg2=default</em>')

    def __unicode__(self):
        return self.name

src/rfdoc/rfdocapp/views/index.py
# Copyright 2009-2013 Nokia Siemens Networks Oyj
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.shortcuts import render

from rfdoc.rfdocapp.models import Library
from rfdoc.rfdocapp.views.search import SearchForm


def index(request):
    libs = None
    versions = None
    if request.GET.get('sort') == 'version':
        versions = list(Library.objects.values('version').distinct())
        versions.sort(key=lambda s: s['version'].split('.'), reverse=True)
        for version in versions:
            version['libs'] = [lib.name for lib in Library.objects.filter(version=version['version'])]
    else:
        libs = Library.objects.values('name').distinct()
        for lib in libs:
            versioned_libs = Library.objects.filter(name=lib['name'])
            if len(versioned_libs) > 1:
                lib['versions'] = [library.version for library in versioned_libs]
    return render(request, 'index.html', {
        'libs': libs,
        'versions': versions,
        'form': SearchForm()
        }
    )

src/rfdoc/rfdocapp/views/library.py
# Copyright 2009-2013 Nokia Siemens Networks Oyj
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re
from django.shortcuts import render, get_list_or_404

from django.http import Http404
from urllib.parse import unquote

from rfdoc.rfdocapp import utils
from rfdoc.rfdocapp.models import Library


def library(request, libname, version=None):
    libname = unquote(libname)
    if version:
        version = unquote(version)
        lib = Library.objects.filter(name=libname, version=version).get()
    else:
        lib = Library.objects.filter(name=libname).order_by('id')[0:1].get()
    if not lib:
        raise Http404('No library matches the given query.')
    libdoc = LibraryDoc(lib)
    versions = [x.version for x in Library.objects.filter(name=libname) if x.version != lib.version]
    versions.sort(key=lambda s: s.split('.'), reverse=True)
    return render(request, 'library.html', {'lib': libdoc, 'versions': versions})


class _DocHelper:
    # This code is adapted from libdoc.py, see
    # http://code.google.com/p/robotframework/wiki/LibraryDocumentationTool

    _name_regexp = re.compile("`(.+?)`")

    def _get_htmldoc(self):
        doc = utils.html_escape(self._doc, formatting=True)
        return self._name_regexp.sub(self._link_keywords, doc)

    def _link_keywords(self, res):
        name = res.group(1)
        keywords = self.keywords if isinstance(self, LibraryDoc) else self._library.keywords
        for kw in keywords:
            if utils.eq(name, kw.name):
                return '<a href="#%s" class="name">%s</a>' %\
                       (kw.name.replace(' ', ''), name)
        if utils.eq_any(name, ['introduction', 'library introduction']):
            return '<a href="#introduction" class="name">%s</a>' % name
        if utils.eq_any(name, ['importing', 'library importing']):
            return '<a href="#importing" class="name">%s</a>' % name
        return '<span class="name">%s</span>' % name

    doc = property(_get_htmldoc)


class LibraryDoc(_DocHelper):

    def __init__(self, libdata):
        self.name = libdata.name
        self._doc = libdata.doc
        self.version = libdata.version
        self.inits = [ KeywordDoc(initdata, self)
                       for initdata in libdata.init_set.all() ]
        self.keywords = [ KeywordDoc(kwdata, self)
                          for kwdata in libdata.keyword_set.all() ]


class KeywordDoc(_DocHelper):

    def __init__(self, kwdata, library):
        self.name = kwdata.name
        self.args = kwdata.args
        self._doc = kwdata.doc
        self.shortdoc = self._doc.split('\n')[0]
        self._library = library

src/rfdoc/rfdocapp/views/search.py
# Copyright 2009-2013 Nokia Siemens Networks Oyj
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re
from django import forms
from django.db.models import Q
from django.shortcuts import render

from rfdoc.rfdocapp.models import Keyword


def search(request):
    search_performed = False
    kws = []
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            term = form.cleaned_data['search_term']
            version = form.cleaned_data['search_version']
            query = Q(name__icontains = term)
            if form.cleaned_data['include_doc']:
                query = query | Q(doc__icontains = term)
            # SQLite LIKEs are case-insensitive by default.
            # Thus using just name__contains wouldn't work expectedly.
            # To circumvent this, an additional query using regular expressions
            # is applied for the case-sensitive searches.
            if not form.cleaned_data['case_insensitive']:
                query = Q(name__regex = r'.*%s.*' % re.escape(term))
                if form.cleaned_data['include_doc']:
                    query = query | Q(doc__regex = r'.*%s.*' % re.escape(term))
            kws = Keyword.objects.filter(query)
            if version:
                version = re.escape(version).replace('\?','.').replace('\*','.*')
                kws = kws.filter(library__version__regex=r'^%s$' % version)
            search_performed = True
    else:
        form = SearchForm()
    return render(request, 'search.html', {
            'form': form,
            'kws': kws,
            'search_performed': search_performed
        }
    )


class SearchForm(forms.Form):
    search_term = forms.CharField(error_messages={'required': 'Search term is required!'})
    search_version = forms.CharField(required=False)
    include_doc = forms.BooleanField(required=False, initial=True)
    case_insensitive = forms.BooleanField(required=False, initial=True)

src/rfdoc/rfdocapp/views/upload.py
# Copyright 2009-2013 Nokia Siemens Networks Oyj
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django import forms
from django.forms.utils import ErrorList
from django.shortcuts import render
from xml.etree import cElementTree as ET

from rfdoc.rfdocapp.models import Library


def upload(request):
    lib = None
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            lib = form.parse_kw_spec(request.FILES['file'],
                                         form.cleaned_data['override'],
                                         form.cleaned_data['override_name'].strip(),
                                         form.cleaned_data['override_version'].strip())
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {
            'form': form,
            'lib': lib
        }
    )


class UploadFileForm(forms.Form):
    file = forms.FileField()
    file.widget.attrs['size'] = 40
    override = forms.BooleanField(required=False)
    override_name = forms.CharField(required=False)
    override_version = forms.CharField(required=False)
    override_version.widget.attrs['size'] = 10

    def parse_kw_spec(self, fileobj, override, override_name, override_version):
        try:
            libdata = LibraryData(fileobj)
            if override_version:
                libdata.version = override_version
            if override_name:
                libdata.name = override_name
            if Library.objects.filter(name=libdata.name).filter(version=libdata.version):
                if not override:
                    raise InvalidXmlError("Library %s version %s already exists." % (libdata.name, libdata.version))
                else:
                    Library.objects.filter(name=libdata.name).filter(version=libdata.version).delete()
            lib = Library(name=libdata.name, doc=libdata.doc, version=libdata.version)
            lib.save()
            for init in libdata.inits:
                lib.init_set.create(doc=init.doc, args=init.args)
            for kw in libdata.kws:
                lib.keyword_set.create(name=kw.name, doc=kw.doc, args=kw.args)
        except InvalidXmlError as err:
            self._errors['file'] = ErrorList([str(err)])
            return None
        return lib


class LibraryData(object):

    def __init__(self, fileobj):
        self.filename = fileobj.name
        root = self._get_root(fileobj)
        try:
            self.name = self._get_name(root)
            self.version = self._get_version(root)
            self.doc = self._get_doc(root)
        except InvalidXmlError as e:
            raise InvalidXmlError('Library parsing error. Given file %s contains invalid XML: %s' % (self.filename, e))
        self.inits = [ InitData(data, self.filename) for data in self._get_inits(root) ]
        self.kws = [ KeywordData(data, self.filename) for data in self._get_keywords(root) ]

    def _get_root(self, fileobj):
        try:
            root = ET.parse(fileobj).getroot()
        except SyntaxError as e:
            raise InvalidXmlError('Given file %s is not XML: %s' % (self.filename, e))
        if root.tag != 'keywordspec':
            raise InvalidXmlError('Given file %s contains invalid XML: Root tag must be keywordspec' % self.filename)
        return root

    def _get_name(self, elem):
        return get_attr(elem, 'name')

    def _get_doc(self, elem):
        return get_child_element(elem, 'doc').text or ''

    def _get_version(self, elem):
        # libdoc.py didn't add version in 2.1 and earlier
        try:
            version_elem = get_child_element(elem, 'version')
        except InvalidXmlError:
            version = None
        else:
            version = version_elem.text
        return version or '<unknown>'

    def _get_inits(self, elem):
        return elem.findall('init')

    def _get_keywords(self, elem):
        # 'keywords/kw' is backwards compatibility for libdoc.py 2.1 and earlier
        kws = elem.findall('keywords/kw') + elem.findall('kw')
        if not kws:
            raise InvalidXmlError('Given test library file %s contains no keywords.' % self.filename)
        return kws


class KeywordData(object):

    def __init__(self, elem, filename):
        try:
            self.name = self._get_name(elem)
            self.doc = self._get_doc(elem)
            self.args = ', '.join(arg.text for arg in self._get_args(elem))
        except InvalidXmlError as e:
            raise InvalidXmlError('Keyword parsing error. Given file %s contains invalid XML: %s' % (filename, e))

    def _get_name(self, elem):
        return get_attr(elem, 'name')

    def _get_doc(self, elem):
        return get_child_element(elem, 'doc').text or ''

    def _get_args(self, elem):
        return get_child_element(elem, 'arguments').findall('arg')


class InitData(KeywordData):

    def _get_name(self, elem):
        return '<init>'


def get_attr(elem, attr_name):
    attr = elem.get(attr_name)
    if not attr:
        raise InvalidXmlError('Attribute %s not found' % attr_name)
    return attr

def get_child_element(elem, child_name):
    child = elem.find(child_name)
    if child is None:
        raise InvalidXmlError('Child element %s not found' % child_name)
    return child


class InvalidXmlError(TypeError):
    pass

src/rfdoc/rfdocapp/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<!--
Copyright 2009-2013 Nokia Siemens Networks Oyj

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
{% load static %}
<html>
<head>
  <title>RFDoc | {% block title %}{% endblock title %}</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'default.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'print.css' %}" media="print">
  <script type="text/javascript" src="{% static 'jquery-1.11.0.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'rfdoc.js' %}"></script>
</head>

<body>
  <div id="header">
    <h1><a href="{% url 'root' %}">RFDoc</a></h1>
    <div id="navigation">{% block navi %}[<a href="{% url 'root' %}">front page</a>]{% endblock navi %}</div>
  </div>

  <div id="content">{% block content %}{% endblock content %}  </div>

  <div id="footer">
    <p>
      <a href="http://code.google.com/p/rfdoc" title="RFDoc project pages">RFDoc</a>
      &nbsp; &nbsp; | &nbsp; &nbsp;
      <a href="http://robotframework.org" title="Robot Framework project pages">Robot Framework</a>
      &nbsp; &nbsp; | &nbsp; &nbsp;
      <a href="http://code.google.com/p/robotframework/wiki/LibraryDocumentationTool" title="Tool for generating library and resource file documentations">libdoc.py</a>
    </p>
  </div>
  {% block outside %}{% endblock outside %}
</body>
</html>

src/rfdoc/rfdocapp/templates/index.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock title %}
{% block navi %}[<a href="{% url 'upload' %}">upload</a>]{% endblock navi %}
{% block content %}
    <h2>Welcome</h2>
    <p class="info">
      RFDoc is a web application for storing and searching Robot Framework
      test library and resource file documentations.
    </p>

    <div class="hr"><hr /></div>
    {% include "search_form.html" %}
    <div class="hr"><hr /></div>

    <h2>Libraries</h2>
    {% if libs %}
      <a class="sortlink" href="?sort=version">Sort by version</a>
      <ul class="libraries">
      {% for lib in libs %}<li><a href="{% url 'library' lib.name|urlencode %}">{{ lib.name }}</a> {% if lib.versions %}( {{ lib.versions|length }} versions )</span>{% endif %}</li>
      {% endfor %}</ul>
    {% elif versions %}
      <a class="sortlink" href="?sort=libname">Sort by library name</a>
      <div class="versioncontainer">
      {% for version in versions %}
        <div>
          <h3>{{ version.version }}</h3>
          <ul>
            {% for lib in version.libs %}
              <li><a href="{% url 'version' lib|urlencode version.version|urlencode %}">{{ lib }}</a></li>
            {% endfor %}
          </ul>
        </div>
      {% endfor %}
      </div>
    <div style="clear:both;">&nbsp;</div>
    {% else %}<p class="info">
      No libraries in the system. Why don't you <a href="{% url 'upload' %}">upload</a> one?
    </p>
    {%endif %}
{% endblock content %}

src/rfdoc/rfdocapp/templates/library.html
{% extends "base.html" %}
{% load rfdoc_filters %}

{% block title %}{{ lib.name }}{% endblock title %}
{% block content %}
    <h2>{{ lib.name }}</h2>
    <p class="version">
      <b>Version:</b> {{ lib.version }}
    </p>
    <h3 id="introduction">Introduction</h3>
      <p class="libintro">{{ lib.doc|safe }}</p>
    {% if lib.inits %}
    <h3 id="importing">Importing</h3>
    <table class="keywords">
      <tr>
        <th class="arg">Arguments</th>
        <th class="doc">Documentation</th>
      </tr>
      {% for init in lib.inits %}
      <tr>
        <td class="arg">{{ init.args }}</td>
        <td class="doc">{{ init.doc|safe }}</td>
      </tr>
      {% endfor %}
    </table>
    {% endif %}
    <h3>Shortcuts</h3>
    <div class='shortcuts'>{% for kw in lib.keywords %}
      <a href="#{{ kw.name|nospaces }}" title="{{ kw.shortdoc }}">{{ kw.name }}</a>{% if not forloop.last %} &middot; {% endif %}{% endfor %}
    </div>

    <h3>Keywords</h3>
    <table class="keywords">
      <tr>
        <th class="kw">Keyword</th>
        <th class="arg">Arguments</th>
        <th class="doc">Documentation</th>
      </tr>
      {% for kw in lib.keywords %}
      <tr>
        <td class="kw" id="{{ kw.name|nospaces }}">{{ kw.name }}</td>
        <td class="arg">{{ kw.args }}</td>
        <td class="doc">{{ kw.doc|safe }}</td>
      </tr>
      {% endfor %}
    </table>
    <div class="hr"><hr /></div>
    <p class="info">Altogether {{ lib.keywords|length }} keywords.</p>
{% endblock content %}
{% block outside %}
    {% if versions %}
    <div id="versions">
        <span class="versions-current">v: {{ lib.version }}</span>
               <dl>
                <dt>Other versions:</dt>
                {% for version in versions %}
                   <dd><a href="{% url 'version' lib.name|urlencode version|urlencode %}">{{ version }}</a></dd>
                {% endfor %}
               </dl>
    </div>
    {% endif %}
{% endblock outside %}

src/rfdoc/rfdocapp/templates/search.html
{% extends "base.html" %}
{% load rfdoc_filters %}

{% block title %}Search{% endblock title %}
{% block content %}{% include "search_form.html" %}{% if search_performed %}
    <div class="hr"><hr /></div>

    <h2>Search results</h2>
    <p class="info">
      {% if not kws %}No{% else %}{{ kws|length }}{% endif %} matching keyword{{ kws|length|pluralize }} found.
    </p>{% if kws %}
    <table class="keywords results">
      <tr>
          <th>Keyword</th>
          <th>Library</th>
          <th>Version</th>
          <th>Doc</th>
      </tr>
      {% for kw in kws %}
      <tr>
        <td><a href="{% url 'version' kw.library.name|urlencode kw.library.version|urlencode %}#{{ kw.name|nospaces }}">{{ kw.name }}</a></td>
        <td><a href="{% url 'version' kw.library.name|urlencode kw.library.version|urlencode %}">{{ kw.library.name }}</a></td>
        <td>{{ kw.library.version }}</td>
        <td>{{ kw.doc|first_line }}</td>
      </tr>
      {% endfor %}
  </table>{% endif %}{% endif %}
{% endblock content %}

src/rfdoc/rfdocapp/templates/search_form.html
    <h2>Search keywords</h2>
    <form enctype="multipart/form-data" action="{% url 'search' %}" method="POST">
      {{ form.search_term.errors }}<table id="search">
        <tr>
          <td><label for="id_search_term">Search term</label></td>
          <td>{{ form.search_term }}</td>
          <td>
            {{ form.include_doc }}
            <label for="id_include_doc">Also documentation</label>
          </td>
          <td>
            {{ form.case_insensitive }}
            <label for="id_case_insensitive">Case-insensitive</label>
          </td>
        </tr>
        <tr>
          <td><label for="id_search_version">Version filter</label></td>
          <td>{{ form.search_version }}</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="search_button" value="Search" />
                <a class="help" href="#">Show help</a>
            </td>
            <td></td>
            <td></td>
        </tr>
      </table>
      <div class="help">
        <h3>Search options:</h3>
        <table>
            <tr>
                <th>Search term</th>
                <td>Text needs to only match a part of the keywords and/or documentation.</td>
            </tr>
            <tr>
                <th>Also Documentation</th>
                <td>Search also keyword documentation.</td>
            </tr>
            <tr>
                <th>Case-insensitive</th>
                <td>Make the search term case-insensitive.</td>
            </tr>
            <tr>
                <th>Version filter</th>
                <td>Only match the versions matching the filter term. The term be an exact match but wild cards
                ? (one character) and * (any number of characters) are supported.</td>
            </tr>
        </table>
      </div>
    </form>

src/rfdoc/rfdocapp/templates/upload.html
{% extends "base.html" %}

{% block title %}Upload{% endblock title %}
{% block content %}
    <h2>Upload documentation</h2>
    <p class="info">
      Select an XML file containing library or resource file
      documentation. These files can be created using
      <a href="http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#libdoc">libdoc.py</a>
      tool.
    </p>

    <div class="hr"><hr /></div>

    <form enctype="multipart/form-data" action="{% url 'upload' %}" method="POST">{% if lib %}
      <div class="success">
        Successfully uploaded library <a href="{% url 'version' lib.name|urlencode lib.version|urlencode %}">{{ lib.name }}</a>.
      </div>{% endif %}{{ form.file.errors }}
      <div>
        {{ form.file }}
      </div>
      <div class="form-options">
          <table>
              <tr>
                  <td><label for="id_override_name">Overwrite library name with:</label></td>
                  <td>{{ form.override_name }}</td>
              </tr>
              <tr>
                  <td><label for="id_override_version">Overwrite library version with:</label></td>
                  <td>{{ form.override_version }}</td>
              </tr>
              <tr>
                  <td><label for="id_override">Overwrite existing documentation with same name and version</label></td>
                  <td>{{ form.override }}</td>
              </tr>
          </table>
      </div>
      <p>
        <input type="submit" value="Upload" />
      </p>
    </form>
{% endblock content %}